// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Wp_ThsRJsNmRjVxPzqDh0QU4sUK34LE',
    appId: '1:23328293886:web:0f7239e3621103a6d6f6af',
    messagingSenderId: '23328293886',
    projectId: 'ands-loot-bazar',
    authDomain: 'ands-loot-bazar.firebaseapp.com',
    storageBucket: 'ands-loot-bazar.appspot.com',
    measurementId: 'G-QM2HX6S714',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZt8pKRJlQgviJWk5NSLEYVPfSuaChxDE',
    appId: '1:23328293886:android:60896cf50c833ba5d6f6af',
    messagingSenderId: '23328293886',
    projectId: 'ands-loot-bazar',
    storageBucket: 'ands-loot-bazar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzm5exujNgdf7wvyvePJYQ7JJA6uAT0p4',
    appId: '1:23328293886:ios:c172c4501694a907d6f6af',
    messagingSenderId: '23328293886',
    projectId: 'ands-loot-bazar',
    storageBucket: 'ands-loot-bazar.appspot.com',
    iosBundleId: 'com.example.ecomm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzm5exujNgdf7wvyvePJYQ7JJA6uAT0p4',
    appId: '1:23328293886:ios:c172c4501694a907d6f6af',
    messagingSenderId: '23328293886',
    projectId: 'ands-loot-bazar',
    storageBucket: 'ands-loot-bazar.appspot.com',
    iosBundleId: 'com.example.ecomm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Wp_ThsRJsNmRjVxPzqDh0QU4sUK34LE',
    appId: '1:23328293886:web:ca092cdc228b8f44d6f6af',
    messagingSenderId: '23328293886',
    projectId: 'ands-loot-bazar',
    authDomain: 'ands-loot-bazar.firebaseapp.com',
    storageBucket: 'ands-loot-bazar.appspot.com',
    measurementId: 'G-NMR8JEPTD7',
  );
}
